# Generated by Django 6.0.6 on 2026-06-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost/amount for the campaign', max_digits=12),
        ),
    ]
