# Generated by Django 6.0.6 on 2026-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Plastic Bags, Paper Glass', max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
